#pragma once
#include <sine_esc.SetThrottleSettings2_req.h>
#include <sine_esc.SetThrottleSettings2_res.h>

#define SINE_ESC_SETTHROTTLESETTINGS2_ID 213
#define SINE_ESC_SETTHROTTLESETTINGS2_SIGNATURE (0x81B48C174CDA4C7AULL)

#if defined(__cplusplus) && defined(DRONECAN_CXX_WRAPPERS)
#include <canard/cxx_wrappers.h>
SERVICE_MESSAGE_CXX_IFACE(sine_esc_SetThrottleSettings2, SINE_ESC_SETTHROTTLESETTINGS2_ID, SINE_ESC_SETTHROTTLESETTINGS2_SIGNATURE, SINE_ESC_SETTHROTTLESETTINGS2_REQUEST_MAX_SIZE, SINE_ESC_SETTHROTTLESETTINGS2_RESPONSE_MAX_SIZE);
#endif
