#pragma once
#include <sine_esc.SetMechanicalAngleEnable_req.h>
#include <sine_esc.SetMechanicalAngleEnable_res.h>

#define SINE_ESC_SETMECHANICALANGLEENABLE_ID 215
#define SINE_ESC_SETMECHANICALANGLEENABLE_SIGNATURE (0x8776979B269EFCFFULL)

#if defined(__cplusplus) && defined(DRONECAN_CXX_WRAPPERS)
#include <canard/cxx_wrappers.h>
SERVICE_MESSAGE_CXX_IFACE(sine_esc_SetMechanicalAngleEnable, SINE_ESC_SETMECHANICALANGLEENABLE_ID, SINE_ESC_SETMECHANICALANGLEENABLE_SIGNATURE, SINE_ESC_SETMECHANICALANGLEENABLE_REQUEST_MAX_SIZE, SINE_ESC_SETMECHANICALANGLEENABLE_RESPONSE_MAX_SIZE);
#endif
