#pragma once
#include <sine_esc.GetPositionCalibration_req.h>
#include <sine_esc.GetPositionCalibration_res.h>

#define SINE_ESC_GETPOSITIONCALIBRATION_ID 226
#define SINE_ESC_GETPOSITIONCALIBRATION_SIGNATURE (0xA895FDA3617029D2ULL)

#if defined(__cplusplus) && defined(DRONECAN_CXX_WRAPPERS)
#include <canard/cxx_wrappers.h>
SERVICE_MESSAGE_CXX_IFACE(sine_esc_GetPositionCalibration, SINE_ESC_GETPOSITIONCALIBRATION_ID, SINE_ESC_GETPOSITIONCALIBRATION_SIGNATURE, SINE_ESC_GETPOSITIONCALIBRATION_REQUEST_MAX_SIZE, SINE_ESC_GETPOSITIONCALIBRATION_RESPONSE_MAX_SIZE);
#endif
