#pragma once
#include <sine_esc.GetRotationSpeedSettings_req.h>
#include <sine_esc.GetRotationSpeedSettings_res.h>

#define SINE_ESC_GETROTATIONSPEEDSETTINGS_ID 212
#define SINE_ESC_GETROTATIONSPEEDSETTINGS_SIGNATURE (0x4461BB2B55B3F410ULL)

#if defined(__cplusplus) && defined(DRONECAN_CXX_WRAPPERS)
#include <canard/cxx_wrappers.h>
SERVICE_MESSAGE_CXX_IFACE(sine_esc_GetRotationSpeedSettings, SINE_ESC_GETROTATIONSPEEDSETTINGS_ID, SINE_ESC_GETROTATIONSPEEDSETTINGS_SIGNATURE, SINE_ESC_GETROTATIONSPEEDSETTINGS_REQUEST_MAX_SIZE, SINE_ESC_GETROTATIONSPEEDSETTINGS_RESPONSE_MAX_SIZE);
#endif
